import random

# Generate random integers and write to file
# count: number of random integers to generate
# filename: output file path
def generate_random_numbers(count, filename):
    with open(filename, 'w') as f:
        for _ in range(count):
            #The range for random numbers generated by the $RANDOM env variable
            #is 0 to 32767.  Code generates random numbers in same range.
            f.write(f"{random.randint(0, 32767)}\n")

# Main entry point
# filename: output file path
def main(filename):
    generate_random_numbers(1000, filename)

if __name__ == "__main__":
    main("file2.txt")
